language: vhdl
os: linux

before_install:
    - sudo apt-get update
    - sudo apt-get install -y gnat zlib1g-dev
    - git clone https://github.com/ghdl/ghdl

install:
    - cd ghdl
    - git pull origin master
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - sudo ldconfig
    - cd ..

script:
    - make test

after_script:
    - make clean

cache:
    directories:
        - /home/travis/build/Lukeekul/TinyFive/ghdl
