language: vhdl
os: linux

before_install:
    - sudo apt-get update
    - sudo apt-get install -y gnat zlib1g-dev

install:
    - git clone https://github.com/ghdl/ghdl
    - cd ghdl
    - .configure --prefix=/usr/local
    - make
    - sudo make install
    - sudo ldconfig

after_install:
    - cd ~

script:
    - make test

after_script:
    - make clean
